In [2]:
import numpy as np

In [13]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=float)
print(array)

[1. 2. 3. 4. 5. 6.]


In [14]:
# number of dimensions
print(array.ndim)

#type of data in array
print(array.dtype)

1
float64


In [15]:
print(array.mean())

3.5


In [17]:
arr2 = np.array([[1, 2, 3, 4, 5, 6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
arr2.reshape(3, 2)



[[1 2 3 4 5 6]]
2
(1, 6)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
arr3 = np.array([[[1, 2], [3, 4], [5, 6]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2]
  [3 4]
  [5 6]]]
3
(1, 3, 2)


In [31]:
arr3d = np.array([[[[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                  
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                  
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]]],                 
                 [[[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                  
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                  
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]]],                  
                 [[[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                  
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]],                 
                 [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]], 
                 [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]]]])
print(arr3d.shape)

(3, 5, 3, 4, 5)


In [40]:
arr = np.arange(1, 100, 2)
print(arr.reshape((10, 5)))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [43]:
# Identity matrix
arr = np.eye((3), dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [46]:
# Matrix filled with ones
one = np.ones((4, 4))
print(one)
print(one.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [47]:
#matrix filled with zeroes
zero = np.zeros((5, 5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [55]:
# to fill the array with a particular value
# the array has to be already created
# default type float
print(zero.fill(7))
print(zero)

None
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [56]:
# to initialize a array with value at creation
# default int datatype
five = np.full((5, 5), 5)
print(five)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [8]:
arr = np.arange(1, 31).reshape((5, 6))
print(arr)
print(arr.shape)
print(arr[1, 3: 5])
# the first argument is slicing of rows, second is slicing of columns
print(arr[1:3, 3])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)
[10 11]
[10 16]


In [10]:
print(arr.T)
print(arr.T.shape)

[[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]
(6, 5)


In [11]:
arr1 = np.array([[2, 3], [3, 4], [4, 5]])
arr2 = np.array([[9, 8], [8, 7]])

out = np.dot(arr1, arr2)
print(out)

[[42 37]
 [59 52]
 [76 67]]


In [12]:
# to save the array as a text file
np.savetxt("out_mul_dot.txt", out)

In [14]:
data_read = np.loadtxt("out_mul_dot.txt")
print(data_read)

[[42. 37.]
 [59. 52.]
 [76. 67.]]


In [19]:
# to join the data from matrices
# we can concatenate multiple arrays
np.concatenate((arr1, arr2), axis=0)

array([[2, 3],
       [3, 4],
       [4, 5],
       [9, 8],
       [8, 7]])

In [22]:
# Axis = 1 means column wise combination
np.concatenate((arr1.T, arr2), axis = 1)

array([[2, 3, 4, 9, 8],
       [3, 4, 5, 8, 7]])

In [23]:
print(np.append(arr2, [[4, 3]], axis = 0))

[[9 8]
 [8 7]
 [4 3]]
