In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("ds_salaries.csv")
print(data.shape)

(3755, 11)


In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   work_year           3755 non-null   int64 
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64 
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64 
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64 
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB
None


In [19]:
# to print first 5 rows
print(data.head())
print(data.head().to_numpy())

   work_year  salary  salary_in_usd  remote_ratio
0       2023   80000          85847           100
1       2023   30000          30000           100
2       2023   25500          25500           100
3       2023  175000         175000           100
4       2023  120000         120000           100
[[  2023  80000  85847    100]
 [  2023  30000  30000    100]
 [  2023  25500  25500    100]
 [  2023 175000 175000    100]
 [  2023 120000 120000    100]]


In [20]:
# to obtain a part of the data initially
# , index_col='work_year'
# skiprows=[3, 4, 5] or skiprows=range(3, 6)
# na_values
# na_filter can be used to handle NaN(Null) values, set to false to replace them to empty string
data = pd.read_csv("ds_salaries.csv", nrows=10, usecols=['work_year', 'salary', 'salary_in_usd', 'remote_ratio'])
print(data.shape)
print(data)

(10, 4)
   work_year  salary  salary_in_usd  remote_ratio
0       2023   80000          85847           100
1       2023   30000          30000           100
2       2023   25500          25500           100
3       2023  175000         175000           100
4       2023  120000         120000           100
5       2023  222200         222200             0
6       2023  136000         136000             0
7       2023  219000         219000             0
8       2023  141000         141000             0
9       2023  147100         147100             0


In [21]:
# to handle NaN values
# data.drop_na(axis=0, inplace=True)
#axis=0 is rowwise removing, the inplace will update the data as well

#to replace the Nan with a suitable value, we can use apply
# data['salary'] = data['salary'].apply(lambda x: data['salary'].mean if np.isnan(x) else x )

In [22]:
# Another way to handle nan
data['salary'].fillna(data['salary'].mean, inplace=True)
#or
data['salary'].fillna(data['salary'].mean, inplace=True)

In [24]:
data.to_excel("processed_data.xlsx", sheet_name="filled-values")

In [25]:
# to merge 2 dataframes
#df1.merge(df2, 'inner')
#data.drop('remote_ratio', axis=1, inplace=True) we have to set axis=1 as we want to delete column not row


In [44]:
#task

df1 = pd.DataFrame([[1, 2, 3], 
                   [4, np.nan, 6], 
                   [7, 8, 9], 
                   [10, 11, np.nan], 
                   [13, 14, 15], 
                  [np.nan, 17, 18]], columns=['a', 'b', 'c'])

df2 = pd.DataFrame([[11, 12, 13], 
                   [14, np.nan, 16], 
                   [17, 18, 19], 
                   [100, 110, np.nan], 
                   [113, 114, 115], 
                  [np.nan, 117, 118]], columns=['a', 'b', 'g'])

df1.fillna(df1.median(), inplace=True)
df2.fillna(df2.median(), inplace=True)

final = df1.merge(df2, 'cross')
final.to_excel('task_excel.xlsx', index=False)
# print(df2)

In [41]:
df1.fillna(df1.median(), inplace=True)
df2.fillna(df2.median(), inplace=True)
print(df1)
print(df2)

      a     b     c
0   1.0   2.0   3.0
1   4.0  11.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0   9.0
4  13.0  14.0  15.0
5   7.0  17.0  18.0
       a      b      g
0   11.0   12.0   13.0
1   14.0  110.0   16.0
2   17.0   18.0   19.0
3  100.0  110.0   19.0
4  113.0  114.0  115.0
5   17.0  117.0  118.0


In [43]:
final = df1.merge(df2, 'cross')
final.to_excel('task_excel.xlsx', index=False)